# Site settings
title: TheDeploymentGuy
description: 'TheDeploymentGuy - TechDaiy By SK - Blend of Devops and BigData'
#url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/blog/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Shailendra Kumar'
  email: emailtoshailendra@gmail.com
  twitter_username: joshgerdes
  facebook_username: shailu.foru
  github_username:  kshailen
  linkedin_username:  unixkshailen

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
