# Site settings
title: TheDeploymentGuy
description: 'DevOps Consultant. Passionate about Devops, BigData, Virutalization, linux, and microservices. I always love to discuss about KVM, Openstack, vagrant, coreOS, Docker, Containers, Python, Shell scripting, etc'
url: 'https://thedeploymentguy.github.io/blog/'
baseurl: '/'
google_analytics: 'UA-104483098-1'
disqus_shortname: 'thedeploymentguy'

author:
  name: 'Shailendra Kumar'
  email: hello@thedeploymentguy.com
  twitter_username:  KumarShailend
  facebook_username: thedeploymentguy
  github_username:  thedeploymentguy
  linkedin_username:  shaikuma

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
