encoding: utf-8

# Site settings
title: The Deployment Guy
description: 'DevOps Consultant. Passionate about Devops, BigData, Virutalization, linux, and microservices. Loves programming in bash and Python. Always love to discuss about KVM, Openstack, vagrant, coreOS, Docker, Containers etc'
url: 'http://127.0.0.1:4000'
baseurl: '/'
google_analytics: 'UA-104483098-1'
disqus_shortname: 'thedeploymentguy'

author:
  name: 'Shailendra Kumar'
  email: emailtoshailendra@gmal.com
  twitter_username:  KumarShailend
  facebook_username: shailu.foru
  github_username:  kshailen
  linkedin_username:  unixkshailen

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-redirect-from']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
